version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts    
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker_volumes/jenkins_home:/var/jenkins_home
  
  tomcat:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8888:8080

