version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts    
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker_volumes/jenkins_home:/var/jenkins_home
  
  tomcat:
    image: tomcat:9.0
    ports:
      - 8888:8080
    volumes:
     - ./docker_volumes/tomcat/config:/usr/local/tomcat/conf
     - ./web-server/target/dummy-web-server.war:/usr/local/tomcat/webapps/ROOT.war:ro

